# Generated by Django 3.2.7 on 2021-11-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_activity_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.breed'),
        ),
    ]
