# Generated by Django 3.2.9 on 2021-11-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='blog.breed'),
        ),
    ]
