# Generated by Django 3.2.9 on 2021-11-02 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_rename_dob_dog_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='join',
            field=models.ManyToManyField(related_name='blog_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
