# Generated by Django 3.2.7 on 2021-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
