# Generated by Django 3.2.7 on 2021-11-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_dog_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dob',
        ),
    ]
